#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EtceteraSequence

#include "Basic.hpp"

#include "BP_EtceteraSequence_classes.hpp"
#include "BP_EtceteraSequence_parameters.hpp"


namespace SDK
{

// Function BP_EtceteraSequence.BP_EtceteraSequence_C.SetupFooter
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_EtceteraSequence_C::SetupFooter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "SetupFooter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.SetupBaseWidget
// (BlueprintCallable, BlueprintEvent)

void ABP_EtceteraSequence_C::SetupBaseWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "SetupBaseWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.SetNextEtceteraSequenceState
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEtceteraSequenceMainState              InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEtceteraSequenceMainState              PrevState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::SetNextEtceteraSequenceState(EEtceteraSequenceMainState InState, EEtceteraSequenceMainState PrevState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "SetNextEtceteraSequenceState");

	Params::BP_EtceteraSequence_C_SetNextEtceteraSequenceState Parms{};

	Parms.InState = InState;
	Parms.PrevState = PrevState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.ReturnFromChallengeAndHonor
// (BlueprintCallable, BlueprintEvent)

void ABP_EtceteraSequence_C::ReturnFromChallengeAndHonor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "ReturnFromChallengeAndHonor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnToCreditFadeFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EUnionUIFadeDirection                   FadeDirection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::OnToCreditFadeFinished(EUnionUIFadeDirection FadeDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnToCreditFadeFinished");

	Params::BP_EtceteraSequence_C_OnToCreditFadeFinished Parms{};

	Parms.FadeDirection = FadeDirection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitStateSelectMainEtcetera
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitStateSelectMainEtcetera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitStateSelectMainEtcetera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitStateFullGameStore
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitStateFullGameStore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitStateFullGameStore");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitStateExit
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitStateExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitStateExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitStateEtceteraTop
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitStateEtceteraTop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitStateEtceteraTop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitStateDLC
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitStateDLC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitStateDLC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnInitialize
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnFinalize
// (Event, Protected, BlueprintEvent)

void ABP_EtceteraSequence_C::OnFinalize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnFinalize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnFadeFinishedToJukebox
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EUnionUIFadeDirection                   FadeDirection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::OnFadeFinishedToJukebox(EUnionUIFadeDirection FadeDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnFadeFinishedToJukebox");

	Params::BP_EtceteraSequence_C_OnFadeFinishedToJukebox Parms{};

	Parms.FadeDirection = FadeDirection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnDecisionSelectMainOption
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::OnDecisionSelectMainOption(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnDecisionSelectMainOption");

	Params::BP_EtceteraSequence_C_OnDecisionSelectMainOption Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnDecisionSelectMainButtonEventbyExtraMenu
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EOptionSequenceMainState                ExtraMenu                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::OnDecisionSelectMainButtonEventbyExtraMenu(EOptionSequenceMainState ExtraMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnDecisionSelectMainButtonEventbyExtraMenu");

	Params::BP_EtceteraSequence_C_OnDecisionSelectMainButtonEventbyExtraMenu Parms{};

	Parms.ExtraMenu = ExtraMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.OnCancelSelectMainOption
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::OnCancelSelectMainOption(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "OnCancelSelectMainOption");

	Params::BP_EtceteraSequence_C_OnCancelSelectMainOption Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.HonorTitleChangeToChallengeEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_EtceteraSequence_C::HonorTitleChangeToChallengeEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "HonorTitleChangeToChallengeEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.GetFooter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UObject* ABP_EtceteraSequence_C::GetFooter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "GetFooter");

	Params::BP_EtceteraSequence_C_GetFooter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.ExecuteUbergraph_BP_EtceteraSequence
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::ExecuteUbergraph_BP_EtceteraSequence(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "ExecuteUbergraph_BP_EtceteraSequence");

	Params::BP_EtceteraSequence_C_ExecuteUbergraph_BP_EtceteraSequence Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.DecisionFullGameStoreEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsAccept                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::DecisionFullGameStoreEvent(bool IsAccept)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "DecisionFullGameStoreEvent");

	Params::BP_EtceteraSequence_C_DecisionFullGameStoreEvent Parms{};

	Parms.IsAccept = IsAccept;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.CompletePlatformStoreEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsAccept                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EtceteraSequence_C::CompletePlatformStoreEvent(bool IsAccept)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "CompletePlatformStoreEvent");

	Params::BP_EtceteraSequence_C_CompletePlatformStoreEvent Parms{};

	Parms.IsAccept = IsAccept;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.BndEvt__BP_EtceteraSequence_BPC_OptionState_K2Node_ComponentBoundEvent_1_OnBackEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EtceteraSequence_C::BndEvt__BP_EtceteraSequence_BPC_OptionState_K2Node_ComponentBoundEvent_1_OnBackEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "BndEvt__BP_EtceteraSequence_BPC_OptionState_K2Node_ComponentBoundEvent_1_OnBackEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.BndEvt__BP_EtceteraSequence_BPC_Jukebox_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EtceteraSequence_C::BndEvt__BP_EtceteraSequence_BPC_Jukebox_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "BndEvt__BP_EtceteraSequence_BPC_Jukebox_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.BndEvt__BP_EtceteraSequence_BPC_Hint_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EtceteraSequence_C::BndEvt__BP_EtceteraSequence_BPC_Hint_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "BndEvt__BP_EtceteraSequence_BPC_Hint_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EtceteraSequence.BP_EtceteraSequence_C.BndEvt__BP_EtceteraSequence_BPC_FriendShip_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EtceteraSequence_C::BndEvt__BP_EtceteraSequence_BPC_FriendShip_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EtceteraSequence_C", "BndEvt__BP_EtceteraSequence_BPC_FriendShip_K2Node_ComponentBoundEvent_0_OnBackEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

