#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemLotteryObject

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItemLotteryObject.BP_ItemLotteryObject_C
// 0x0008 (0x12E8 - 0x12E0)
class ABP_ItemLotteryObject_C final : public AItemLotteryObject
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x12E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ItemLotteryObject_C">();
	}
	static class ABP_ItemLotteryObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ItemLotteryObject_C>();
	}
};
static_assert(alignof(ABP_ItemLotteryObject_C) == 0x000008, "Wrong alignment on ABP_ItemLotteryObject_C");
static_assert(sizeof(ABP_ItemLotteryObject_C) == 0x0012E8, "Wrong size on ABP_ItemLotteryObject_C");
static_assert(offsetof(ABP_ItemLotteryObject_C, DefaultSceneRoot) == 0x0012E0, "Member 'ABP_ItemLotteryObject_C::DefaultSceneRoot' has a wrong offset!");

}

