#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RewardDialogAndSave

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_RewardDialogAndSave.BP_RewardDialogAndSave_C.ExecuteUbergraph_BP_RewardDialogAndSave
// 0x0058 (0x0058 - 0x0000)
struct BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsNotEmpty_ReturnValue;             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemGet_Window_C*                  CallFunc_OpenRewardDialog_RewardDialogWidget;      // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_OpenRewardDialog_ZOrder;                  // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller;        // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller_1;      // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave) == 0x000008, "Wrong alignment on BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave");
static_assert(sizeof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave) == 0x000058, "Wrong size on BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, EntryPoint) == 0x000000, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_Array_IsNotEmpty_ReturnValue) == 0x000014, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_Array_IsNotEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_OpenRewardDialog_RewardDialogWidget) == 0x000020, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_OpenRewardDialog_RewardDialogWidget' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_OpenRewardDialog_ZOrder) == 0x000028, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_OpenRewardDialog_ZOrder' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, K2Node_DynamicCast_AsApp_Player_Controller) == 0x000030, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::K2Node_DynamicCast_AsApp_Player_Controller' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_Not_PreBool_ReturnValue) == 0x000039, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_IsValid_ReturnValue) == 0x00003A, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, CallFunc_GetPlayerController_ReturnValue_1) == 0x000040, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, K2Node_DynamicCast_AsApp_Player_Controller_1) == 0x000048, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::K2Node_DynamicCast_AsApp_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'BP_RewardDialogAndSave_C_ExecuteUbergraph_BP_RewardDialogAndSave::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

}

