#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_FriendShip

#include "Basic.hpp"

#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"
#include "UnionUI_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_FriendShip.BPC_FriendShip_C
// 0x00B8 (0x01E0 - 0x0128)
class UBPC_FriendShip_C final : public UFriendShipState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0128(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Friendship_C*                      FriendShipWidget;                                  // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnBackEvent;                                       // 0x0138(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UMenuInputRecieveObject*                SubInputReceiver;                                  // 0x0148(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         UseTicketAmount;                                   // 0x0150(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 RewardGradeTicketAmountSetting;                    // 0x0158(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Remain_NextGradeTicketAmount;                      // 0x0168(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OnePushUseTicketAmount;                            // 0x016C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUnionUIPopupWindowBase*                PopupWindow;                                       // 0x0170(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        UseRepeateTicketAmount;                            // 0x0178(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           PlusTicketTimer;                                   // 0x0180(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           MinusTicketTimer;                                  // 0x0188(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemGet_Window_C*                  RewardGetWindow;                                   // 0x0190(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FRewardGetWindowParam>          Reward_Array;                                      // 0x0198(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         OldGivedTicket;                                    // 0x01A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NewGivedTicket;                                    // 0x01AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHintPopupWindow*                       TipsWindow;                                        // 0x01B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EHintId                                       HintId;                                            // 0x01B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonMenuFooterMenu*                  Footer;                                            // 0x01C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          bSelectingTicket;                                  // 0x01C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMenuPlayerController*                  MenuPlayerController;                              // 0x01D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bPlayedTicketRepeateErrorSe;                       // 0x01D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDisableNextFocusSound;                            // 0x01D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsRepeatedPlusTicketMouse;                        // 0x01DA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsRepeatedMinusTicketMouse;                       // 0x01DB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UseTicketEvent(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void UseTicketClamp(int32 ChangeTicketAmount, bool* bIsNumChanged);
	void UpdateReward(EDriverId DriverId);
	void UpdateFriendShipIcon();
	bool UnregisterSingleSubMenu(class UObject* InMenuObject);
	bool UnregisterMainMenu(class UObject* Object);
	void ShoulderPressedPlusTicketEvent_ForMouse();
	void ShoulderPressedPlusTicketEvent(class UObject* Object);
	void ShoulderPressedMinusTicketEvent_ForMouse();
	void ShoulderPressedMinusTicketEvent(class UObject* Object);
	void SetUseTicketMax_ForMouse();
	void SetUseTicketMax(class UObject* Object);
	void SetSaveDataReward(TArray<struct FRewardGetWindowParam>& InRewardArray);
	void SetMenuDirectionKeyEnable(bool bEnableDirection);
	void SetLastFocusIconEvent(class UObject* Object);
	void SetEnableSubMenuAll(bool IsEnable);
	void SelectTicketPlayedOutAnimationEvent();
	void SelectTicketPlayedInAnimationEvent();
	void RegisterMainMenu(class UObject* Object);
	void PlusTicketRepeateEvent();
	void PlusTicketEvent(int32 UseTicketAmount_0, bool bLRAnimation);
	void PlayTipsWindow();
	void PlayChangeTicketErrorSeEvent();
	void OnTipsWindowCloseEnd_Event();
	void OnTipsSaveComplete(ESaveDataStatus Status);
	void OnInitState();
	void OnFriendShipFinished();
	void OnExitState();
	void OnClosed_ItemGet();
	void NoTicketWindowCloseEvent(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void MinusTicketRepeateEvent();
	void MinusTicketEvent(int32 UseTicketAmount_0, bool bLRAnimation);
	bool IsValidTicketTimer();
	void IconSelectEvent();
	void IconDecisionEvent(int32 PlayerIndex, int32 CharaIndex);
	void GoToFriendShipTopFromTips();
	void GetNewReward(EDriverId DriverId, int32 TicketNum0, int32 TicketNum1, bool* bNewReward, TArray<struct FRewardGetWindowParam>* Output_Get);
	void FriendShipWidgetUnbindsEvent();
	void FriendShipWidgetBindsEvent();
	void FinishedInAnimationEvent();
	void ExecuteUbergraph_BPC_FriendShip(int32 EntryPoint);
	void Event_PlayedGiveAnimation();
	void Event_GoToTop();
	void Event_GivedTicket();
	void Event_GetReward();
	void EnableSelectTicketEvent(bool bEnable, bool bUpdateSubMenu);
	void EnableFriendShipTopEvent(bool bEnable);
	void DisableInputCharacterSelect();
	void CreateWindowNoTicketEvent();
	void CreateWindowFinalCheckEvent(class UObject* Object);
	void CreateTipsWindow(EHintId InHintId);
	void ClearPlusMinusTicketTimer();
	void CancelSelectTicketEvent(class UObject* Object);
	void CancelEvent();
	void CaluculateGrade(int32 ticketNum, int32* Grade, int32* RemainNextGrade, double* RateToNextGrade);
	void BackEtcTopEvent(class UObject* Object);
	void ArrowReleasedPlusTicketEvent_ForMouse();
	void ArrowReleasedPlusTicketEvent(class UObject* Object, EUnionUIControlDir Dir);
	void ArrowReleasedMinusTicketEvent_ForMouse();
	void ArrowReleasedMinusTicketEvent(class UObject* Object, EUnionUIControlDir Dir);
	void ArrowPressedPlusTicketEvent_ForMouse();
	void ArrowPressedPlusTicketEvent(class UObject* Object, EUnionUIControlDir Dir);
	void ArrowPressedMinusTicketEvent_ForMouse();
	void ArrowPressedMinusTicketEvent(class UObject* Object, EUnionUIControlDir Dir);
	void AddRegisterSubMenu(class UObject* InMenuObject, int32 InPriority);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_FriendShip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_FriendShip_C")
	}
	static class UBPC_FriendShip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_FriendShip_C>();
	}
};
DUMPER7_ASSERTS_UBPC_FriendShip_C;

}

