#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_TimeTrialClassSelectSubState

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "UNION_structs.hpp"
#include "UnionUI_structs.hpp"


namespace SDK::Params
{

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.ConvertIndexToClassId
// 0x0008 (0x0008 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             newParam;                                          // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId) == 0x000004, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId) == 0x000008, "Wrong size on BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId, Index_0) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId::Index_0' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId, newParam) == 0x000004, "Member 'BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId::newParam' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId, CallFunc_Conv_IntToByte_ReturnValue) == 0x000005, "Member 'BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId, CallFunc_GetValidValue_ReturnValue) == 0x000006, "Member 'BPC_TimeTrialClassSelectSubState_C_ConvertIndexToClassId::CallFunc_GetValidValue_ReturnValue' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.ExecuteUbergraph_BPC_TimeTrialClassSelectSubState
// 0x0310 (0x0310 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate;         // 0x0008(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EMenuSequenceSubState                         Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSequenceSubState                         Temp_byte_Variable_1;                              // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             Temp_byte_Variable_2;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             Temp_byte_Variable_3;                              // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHintId                                       Temp_byte_Variable_4;                              // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USaveDataManageSubsystem*               CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMenuSoundSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue_1;          // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x2];                                       // 0x0042(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x2];                                       // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded;                         // 0x0058(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsCourse_Select_Widget_Base; // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCourseSelectWidgetBase*                CallFunc_Create_ReturnValue;                       // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller;        // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller_1;      // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UnregisterSingleSubMenu_ReturnValue;      // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AA[0x6];                                       // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerSequence_ReturnValue;             // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetNeedInitFadeOut_ReturnValue;           // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_TimeTrialSequence_C*                K2Node_DynamicCast_AsBP_Time_Trial_Sequence;       // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x00CB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInViewport_ReturnValue;                 // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CourseSelect_TimeTrial_C*          K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial; // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Temp_class_Variable_1;                             // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsWBP_Class_Select_Time_Trial; // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ClassSelect_TimeTrial_C*           CallFunc_Create_ReturnValue_1;                     // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded_1;                       // 0x0100(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInViewport_ReturnValue_1;               // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10A[0x6];                                      // 0x010A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUITransitionManager*              CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInViewport_ReturnValue_2;               // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11A[0x2];                                      // 0x011A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x011C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             CallFunc_GetSelectedMenuSpeedClassId_ReturnValue;  // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13A[0x2];                                      // 0x013A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_2; // 0x013C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_3; // 0x014C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_4; // 0x015C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button_2;                       // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex_2;                   // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex_2;                  // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button_1;                       // 0x0188(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex_1;                   // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex_1;                  // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button;                         // 0x0198(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex;                     // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex;                    // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHintId                                       Temp_byte_Variable_5;                              // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             K2Node_Select_Default;                             // 0x01A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x01AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHintId                                       Temp_byte_Variable_6;                              // 0x01AB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x01AC(0x0004)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x01B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_CourseSelect_TimeTrial_C*          K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_1; // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x3];                                      // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x01CC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1DC[0x4];                                      // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CourseSelect_TimeTrial_C*          K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_2; // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuSequenceUIInterface> CallFunc_SetNextSubMenuSequenceState_self_CastInput; // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUITransitionManager*              CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x0208(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_211[0x3];                                      // 0x0211(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue_1;                  // 0x0214(0x0004)()
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue_2;                  // 0x0218(0x0004)()
	uint8                                         Pad_21C[0x4];                                      // 0x021C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x0220(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMenuPlayerController*                  K2Node_DynamicCast_AsMenu_Player_Controller;       // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastStateIsClassSelect_LClassSelect;   // 0x0231(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_232[0x2];                                      // 0x0232(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EUnionUIFadeDirection FadeDirection)> K2Node_CreateDelegate_OutputDelegate_7;     // 0x0234(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EUnionUIFadeDirection                         K2Node_CustomEvent_FadeDirection;                  // 0x0244(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_245[0x3];                                      // 0x0245(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_5;        // 0x0248(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMenuPlayerController*                  K2Node_DynamicCast_AsMenu_Player_Controller_1;     // 0x0250(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastStateIsClassSelect_LClassSelect_1; // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x025B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue_2;          // 0x0260(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetCurrentTopMenuLevelName_ReturnValue;   // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULevelStreaming*                        CallFunc_GetStreamingLevel_ReturnValue;            // 0x0270(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0278(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALevelScriptActor*                      CallFunc_GetLevelScriptActor_ReturnValue;          // 0x0288(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IMenuLobbyLevelInterface> K2Node_DynamicCast_AsMenu_Lobby_Level_Interface; // 0x0290(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACameraActor*                           CallFunc_GetCameraActor_ReturnValue;               // 0x02A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B1[0x3];                                      // 0x02B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x02B4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetState_ReturnValue;                     // 0x02C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHierarchicalStateMachine*              CallFunc_GetOwnerStateMachine_ReturnValue;         // 0x02C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetCurrentState_ReturnValue;              // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastStateIsClassSelect_LClassSelect_2; // 0x02D5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSequenceSubState                         K2Node_Select_Default_1;                           // 0x02D6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             Temp_byte_Variable_7;                              // 0x02D7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuInputRecieveObject*                CallFunc_SpawnObject_ReturnValue;                  // 0x02D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsReadHint_ReturnValue;                   // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsReadHint_ReturnValue_1;                 // 0x02E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x02E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02E3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x02E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHintId                                       K2Node_Select_Default_2;                           // 0x02E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_3;                // 0x02E6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             Temp_byte_Variable_8;                              // 0x02E7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHintId                                       K2Node_Select_Default_3;                           // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x02EA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastStateIsClassSelect_LClassSelect_3; // 0x02EB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_4;                // 0x02EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             K2Node_Select_Default_4;                           // 0x02ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EE[0x2];                                      // 0x02EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUITransitionManager*              CallFunc_GetGameInstanceSubsystem_ReturnValue_3;   // 0x02F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F9[0x3];                                      // 0x02F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_10;      // 0x02FC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState) == 0x000310, "Wrong size on BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, EntryPoint) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::EntryPoint' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_bool_Variable) == 0x000004, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable) == 0x000018, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_1) == 0x000019, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_int_Variable) == 0x00001C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_2) == 0x000020, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_3) == 0x000021, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_bool_Variable_1) == 0x000022, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_4) == 0x000023, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue) == 0x000024, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000028, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetWorldSubsystem_ReturnValue) == 0x000030, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetWorldSubsystem_ReturnValue_1) == 0x000038, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetWorldSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_MakeLiteralByte_ReturnValue) == 0x000040, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_1) == 0x000041, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000044, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000048, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000049, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00004C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000050, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_Loaded) == 0x000058, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_class_Variable) == 0x000060, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_ClassDynamicCast_AsCourse_Select_Widget_Base) == 0x000068, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_ClassDynamicCast_AsCourse_Select_Widget_Base' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_ClassDynamicCast_bSuccess) == 0x000070, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Create_ReturnValue) == 0x000078, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue) == 0x000080, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsApp_Player_Controller) == 0x000088, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsApp_Player_Controller' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess) == 0x000090, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue_1) == 0x000098, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsApp_Player_Controller_1) == 0x0000A0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsApp_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_1) == 0x0000A8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_UnregisterSingleSubMenu_ReturnValue) == 0x0000A9, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_UnregisterSingleSubMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetOwnerSequence_ReturnValue) == 0x0000B0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetOwnerSequence_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetNeedInitFadeOut_ReturnValue) == 0x0000B8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetNeedInitFadeOut_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsBP_Time_Trial_Sequence) == 0x0000C0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsBP_Time_Trial_Sequence' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_2) == 0x0000C8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_2) == 0x0000C9, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_3) == 0x0000CA, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_4) == 0x0000CB, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsInViewport_ReturnValue) == 0x0000CC, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsInViewport_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial) == 0x0000D0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_3) == 0x0000D8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_class_Variable_1) == 0x0000E0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_class_Variable_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_ClassDynamicCast_AsWBP_Class_Select_Time_Trial) == 0x0000E8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_ClassDynamicCast_AsWBP_Class_Select_Time_Trial' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_ClassDynamicCast_bSuccess_1) == 0x0000F0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Create_ReturnValue_1) == 0x0000F8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_Loaded_1) == 0x000100, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_Loaded_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_5) == 0x000108, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsInViewport_ReturnValue_1) == 0x000109, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsInViewport_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x000110, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_6) == 0x000118, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsInViewport_ReturnValue_2) == 0x000119, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsInViewport_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_1) == 0x00011C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue_2) == 0x000130, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetSelectedMenuSpeedClassId_ReturnValue) == 0x000138, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetSelectedMenuSpeedClassId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000139, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_2) == 0x00013C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_3) == 0x00014C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_4) == 0x00015C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_Button_2) == 0x000170, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_Button_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_PanelIndex_2) == 0x000178, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_PanelIndex_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_ButtonIndex_2) == 0x00017C, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_ButtonIndex_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000180, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_Button_1) == 0x000188, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_Button_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_PanelIndex_1) == 0x000190, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_PanelIndex_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_ButtonIndex_1) == 0x000194, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_ButtonIndex_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_Button) == 0x000198, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_Button' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_PanelIndex) == 0x0001A0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_PanelIndex' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_ButtonIndex) == 0x0001A4, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_ButtonIndex' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_5) == 0x0001A8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_Select_Default) == 0x0001A9, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x0001AA, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_6) == 0x0001AB, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_SoundPlay_ReturnValue) == 0x0001AC, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_SoundPlay_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_5) == 0x0001B0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_1) == 0x0001C0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_4) == 0x0001C8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_6) == 0x0001CC, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_2) == 0x0001E0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsWBP_Course_Select_Time_Trial_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_5) == 0x0001E8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_SetNextSubMenuSequenceState_self_CastInput) == 0x0001F0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_SetNextSubMenuSequenceState_self_CastInput' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue_3) == 0x000200, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetGameInstanceSubsystem_ReturnValue_2) == 0x000208, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetGameInstanceSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_bool_Variable_2) == 0x000210, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_SoundPlay_ReturnValue_1) == 0x000214, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_SoundPlay_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_SoundPlay_ReturnValue_2) == 0x000218, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_SoundPlay_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue_4) == 0x000220, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsMenu_Player_Controller) == 0x000228, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsMenu_Player_Controller' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_6) == 0x000230, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetLastStateIsClassSelect_LClassSelect) == 0x000231, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetLastStateIsClassSelect_LClassSelect' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_7) == 0x000234, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CustomEvent_FadeDirection) == 0x000244, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CustomEvent_FadeDirection' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetPlayerController_ReturnValue_5) == 0x000248, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetPlayerController_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsMenu_Player_Controller_1) == 0x000250, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsMenu_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_7) == 0x000258, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_7) == 0x000259, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetLastStateIsClassSelect_LClassSelect_1) == 0x00025A, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetLastStateIsClassSelect_LClassSelect_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Not_PreBool_ReturnValue) == 0x00025B, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetWorldSubsystem_ReturnValue_2) == 0x000260, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetWorldSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetCurrentTopMenuLevelName_ReturnValue) == 0x000268, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetCurrentTopMenuLevelName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetStreamingLevel_ReturnValue) == 0x000270, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetStreamingLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_8) == 0x000278, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetLevelScriptActor_ReturnValue) == 0x000288, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetLevelScriptActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_AsMenu_Lobby_Level_Interface) == 0x000290, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_AsMenu_Lobby_Level_Interface' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_DynamicCast_bSuccess_8) == 0x0002A0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetCameraActor_ReturnValue) == 0x0002A8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetCameraActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_8) == 0x0002B0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_9) == 0x0002B4, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetState_ReturnValue) == 0x0002C4, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetOwnerStateMachine_ReturnValue) == 0x0002C8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetOwnerStateMachine_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetCurrentState_ReturnValue) == 0x0002D0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetCurrentState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_NotEqual_IntInt_ReturnValue) == 0x0002D4, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetLastStateIsClassSelect_LClassSelect_2) == 0x0002D5, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetLastStateIsClassSelect_LClassSelect_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_Select_Default_1) == 0x0002D6, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_7) == 0x0002D7, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_SpawnObject_ReturnValue) == 0x0002D8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsReadHint_ReturnValue) == 0x0002E0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsReadHint_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsReadHint_ReturnValue_1) == 0x0002E1, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsReadHint_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Not_PreBool_ReturnValue_1) == 0x0002E2, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_BooleanAND_ReturnValue) == 0x0002E3, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Not_PreBool_ReturnValue_2) == 0x0002E4, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_Select_Default_2) == 0x0002E5, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Not_PreBool_ReturnValue_3) == 0x0002E6, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Not_PreBool_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_byte_Variable_8) == 0x0002E7, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_byte_Variable_8' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_Select_Default_3) == 0x0002E8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_9) == 0x0002E9, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, Temp_bool_Variable_3) == 0x0002EA, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetLastStateIsClassSelect_LClassSelect_3) == 0x0002EB, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetLastStateIsClassSelect_LClassSelect_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_Not_PreBool_ReturnValue_4) == 0x0002EC, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_Not_PreBool_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_Select_Default_4) == 0x0002ED, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_GetGameInstanceSubsystem_ReturnValue_3) == 0x0002F0, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_GetGameInstanceSubsystem_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, CallFunc_IsValid_ReturnValue_10) == 0x0002F8, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState, K2Node_CreateDelegate_OutputDelegate_10) == 0x0002FC, "Member 'BPC_TimeTrialClassSelectSubState_C_ExecuteUbergraph_BPC_TimeTrialClassSelectSubState::K2Node_CreateDelegate_OutputDelegate_10' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.GetLastStateIsClassSelect
// 0x0003 (0x0003 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect final
{
public:
	bool                                          LClassSelect;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastStateIsClassSelect_LClassSelect;   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect) == 0x000001, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect) == 0x000003, "Wrong size on BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect, LClassSelect) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect::LClassSelect' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect, CallFunc_GetLastStateIsClassSelect_LClassSelect) == 0x000002, "Member 'BPC_TimeTrialClassSelectSubState_C_GetLastStateIsClassSelect::CallFunc_GetLastStateIsClassSelect_LClassSelect' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnFinishedFade_UIFadeWidget
// 0x0001 (0x0001 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget final
{
public:
	EUnionUIFadeDirection                         FadeDirection;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget) == 0x000001, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget) == 0x000001, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget, FadeDirection) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnFinishedFade_UIFadeWidget::FadeDirection' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnLoaded_2818D6214851B5A07B8199A904D33989
// 0x0008 (0x0008 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989 final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989) == 0x000008, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989, Loaded) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnLoaded_2818D6214851B5A07B8199A904D33989::Loaded' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB
// 0x0008 (0x0008 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB) == 0x000008, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB, Loaded) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnLoaded_DD1A3ABF48F72B256692DBB7C6BF81DB::Loaded' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnUISceneCancel_SelectClassWidget
// 0x0010 (0x0010 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget) == 0x000010, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget, Button) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget::Button' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget, PanelIndex) == 0x000008, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget::PanelIndex' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget, ButtonIndex) == 0x00000C, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneCancel_SelectClassWidget::ButtonIndex' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnUISceneDecision_SelectClassWidget
// 0x0010 (0x0010 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget) == 0x000010, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget, Button) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget::Button' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget, PanelIndex) == 0x000008, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget::PanelIndex' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget, ButtonIndex) == 0x00000C, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneDecision_SelectClassWidget::ButtonIndex' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.OnUISceneFocusEvent_SelectClassWidget
// 0x0010 (0x0010 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget) == 0x000010, "Wrong size on BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget, Button) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget::Button' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget, PanelIndex) == 0x000008, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget::PanelIndex' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget, ButtonIndex) == 0x00000C, "Member 'BPC_TimeTrialClassSelectSubState_C_OnUISceneFocusEvent_SelectClassWidget::ButtonIndex' has a wrong offset!");

// Function BPC_TimeTrialClassSelectSubState.BPC_TimeTrialClassSelectSubState_C.ShowTipsWindow
// 0x0040 (0x0040 - 0x0000)
struct BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow final
{
public:
	EHintId                                       InHintId;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Popup_Window_Hint_C*               CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow) == 0x000008, "Wrong alignment on BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow");
static_assert(sizeof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow) == 0x000040, "Wrong size on BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, InHintId) == 0x000000, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::InHintId' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_MakeLiteralByte_ReturnValue) == 0x000001, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_Create_ReturnValue) == 0x000008, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000010, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_GetWorldSubsystem_ReturnValue) == 0x000018, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow, CallFunc_GetPlayerController_ReturnValue) == 0x000038, "Member 'BPC_TimeTrialClassSelectSubState_C_ShowTipsWindow::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");

}

