#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultLegend

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ResultLegend.WBP_ResultLegend_C
// 0x0018 (0x0340 - 0x0328)
class UWBP_ResultLegend_C final : public UResultRateRank
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_ResultLegend_Sub_Rate_C*           WBP_ResultLegend_Sub_Rate;                         // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	double                                        CurrentGaugeValue;                                 // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ResultLegend(int32 EntryPoint);
	void FinishUpdateRateEvent();
	void InAnimationFinishEvent();
	void OutFinishAnimationEvent();
	void PlayCountDownAnimation();
	void PlayCountUpAnimation();
	void PlayCountUpNUMAnimation();
	void PlayInAnimation();
	void PlayOutAnimation();
	void SetAdjustValue(int32 AdjustValue);
	void SetCurrentGaugeValue(float CurrentValue);
	void SetCurrentRateValue(int32 CurrentRateValue);
	void SetGaugeCurrentAndNextGradeIcon(ELegendCompeRateGrade PrevGradeIcon, ELegendCompeRateGrade CurrentGrade, ELegendCompeRateGrade NextGrade, bool LowestLimitGrade);
	void SetResultIcon(int32 IconIndex);
	void SetTargetGaugeValue(float TargetValue);
	void SetupLimitValue(int32 CurrentRankLimit, int32 NextRankLimit);
	void StartAdjustingGaugeEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ResultLegend_C">();
	}
	static class UWBP_ResultLegend_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ResultLegend_C>();
	}
};
static_assert(alignof(UWBP_ResultLegend_C) == 0x000008, "Wrong alignment on UWBP_ResultLegend_C");
static_assert(sizeof(UWBP_ResultLegend_C) == 0x000340, "Wrong size on UWBP_ResultLegend_C");
static_assert(offsetof(UWBP_ResultLegend_C, UberGraphFrame) == 0x000328, "Member 'UWBP_ResultLegend_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_C, WBP_ResultLegend_Sub_Rate) == 0x000330, "Member 'UWBP_ResultLegend_C::WBP_ResultLegend_Sub_Rate' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_C, CurrentGaugeValue) == 0x000338, "Member 'UWBP_ResultLegend_C::CurrentGaugeValue' has a wrong offset!");

}

