#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_RaceSetting

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Jukebox_Sub_RaceSetting.WBP_Jukebox_Sub_RaceSetting_C
// 0x0010 (0x02F0 - 0x02E0)
class UWBP_Jukebox_Sub_RaceSetting_C final : public UUserWidget
{
public:
	class UImage*                                 NGMark;                                            // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionRichTextBlock*                    TXT_RaceSetting;                                   // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Jukebox_Sub_RaceSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Jukebox_Sub_RaceSetting_C")
	}
	static class UWBP_Jukebox_Sub_RaceSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Jukebox_Sub_RaceSetting_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Jukebox_Sub_RaceSetting_C;

}

