#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultLegend_Sub_Rate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ResultLegend_Sub_Rate.WBP_ResultLegend_Sub_Rate_C
// 0x0250 (0x0628 - 0x03D8)
class UWBP_ResultLegend_Sub_Rate_C final : public UResultRateLegendCompeWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Legend_Out;                                        // 0x03E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Legend_DownGaugeOut;                               // 0x03E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Legend_Loop_CountUp_NUM;                           // 0x03F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Legend_Loop_CountDown;                             // 0x03F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Legend_Loop_CountUp;                               // 0x0400(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Legend_InLoop;                                     // 0x0408(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Base_L;                                            // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Base_L_NonIcon;                                    // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Base_L_NonIcon_01;                                 // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Base_R;                                            // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Base_R_Icon_01;                                    // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Base_R_NonIcon;                                    // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         BaseBG;                                            // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         BaseBG_LeftNonIcon;                                // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         BaseBG_NonIcon;                                    // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BG;                                                // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BG_02_Cover;                                       // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BG_02_Cover_02;                                    // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Center_L;                                          // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Center_R;                                          // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 DMY_LegendGradeIcon_Current;                       // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 DMY_LegendGradeIcon_Next;                          // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         DSP_NUM_Grade_AddEff;                              // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Gauge;                                             // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_1000;                                        // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0_1000;                                      // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0001;                                        // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0001_EFF;                                    // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0010;                                        // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0010_EFF;                                    // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0100;                                        // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0100_EFF;                                    // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0_0001;                                      // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0_0010;                                      // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_0_0100;                                      // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Grade_1000_EFF;                                    // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 L_Line;                                            // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 L_Line_Eff;                                        // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Line;                                              // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         NUM_Grade;                                         // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         NUM_Grade_0000;                                    // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         NUM_Grade_InDecrease;                              // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PAT_PlusMinus;                                     // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlusMinus_1000;                                    // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlusMinus_0001;                                    // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlusMinus_0010;                                    // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlusMinus_0100;                                    // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 R_Line;                                            // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 R_Line_Eff;                                        // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Tri_T;                                             // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Tri_T_Btm;                                         // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Trophy;                                            // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ResultLegend_Sub_NUM_C*            WBP_ResultLegend_Sub_NUM_Current;                  // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ResultLegend_Sub_NUM_C*            WBP_ResultLegend_Sub_NUM_Next;                     // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_GaugeBase;                          // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_UpDwon;                             // 0x0598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Window_L;                                          // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Window_L_1;                                        // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Window_R;                                          // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Window_R_1;                                        // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              StartAdjustingGauge;                               // 0x05C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<ELegendCompeRateGrade, TSoftObjectPtr<class UTexture2D>> LegendGradeIcon;                   // 0x05D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsCountDown;                                       // 0x0620(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddTextImageToTextArray(const TArray<class UImage*>& TargetArray, class UPanelWidget* TextParent);
	void ExecuteUbergraph_WBP_ResultLegend_Sub_Rate(int32 EntryPoint);
	void Finished_0D989C8F445F1F628E2120A88D494244();
	void Finished_7D0AEC914AF50B9180DA47BB577AA564();
	void Finished_FA3822794A885E4D1B40AE97B7C37967();
	void OnLoaded_614E58FB488C4503F994FF8A54908BA9(class UObject* Loaded);
	void OnLoaded_FF8DD9F649CD1B5C771F029C3341E817(class UObject* Loaded);
	void PlayCountDownAnimation();
	void PlayCountUpAnimation();
	void PlayCountUpNUMAnimation();
	void PlayInAnimation();
	void PlayOutAnimation();
	void PreConstruct(bool IsDesignTime);
	void SequenceEvent__ENTRYPOINTWBP_ResultLegend_Sub_Rate();
	void SequenceEvent__ENTRYPOINTWBP_ResultLegend_Sub_Rate_0();
	void SetGaugeCurrentAndNextGradeIcon(ELegendCompeRateGrade PrevGradeIcon, ELegendCompeRateGrade CurrentGradeIcon, ELegendCompeRateGrade NextGradeIcon, bool LowestLimitGrade);
	void StartCountDownEventNotifier();
	void StartCountUpEventNotifier();
	void UpdateCurrentVisibilityByGrade(ELegendCompeRateGrade CurrentGrade, bool IsLowestLimit);
	void UpdateVisibilityWhenFinishUpdateRate();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ResultLegend_Sub_Rate_C">();
	}
	static class UWBP_ResultLegend_Sub_Rate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ResultLegend_Sub_Rate_C>();
	}
};
static_assert(alignof(UWBP_ResultLegend_Sub_Rate_C) == 0x000008, "Wrong alignment on UWBP_ResultLegend_Sub_Rate_C");
static_assert(sizeof(UWBP_ResultLegend_Sub_Rate_C) == 0x000628, "Wrong size on UWBP_ResultLegend_Sub_Rate_C");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, UberGraphFrame) == 0x0003D8, "Member 'UWBP_ResultLegend_Sub_Rate_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_Out) == 0x0003E0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_Out' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_DownGaugeOut) == 0x0003E8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_DownGaugeOut' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_Loop_CountUp_NUM) == 0x0003F0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_Loop_CountUp_NUM' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_Loop_CountDown) == 0x0003F8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_Loop_CountDown' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_Loop_CountUp) == 0x000400, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_Loop_CountUp' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Legend_InLoop) == 0x000408, "Member 'UWBP_ResultLegend_Sub_Rate_C::Legend_InLoop' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_L) == 0x000410, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_L' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_L_NonIcon) == 0x000418, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_L_NonIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_L_NonIcon_01) == 0x000420, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_L_NonIcon_01' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_R) == 0x000428, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_R' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_R_Icon_01) == 0x000430, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_R_Icon_01' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Base_R_NonIcon) == 0x000438, "Member 'UWBP_ResultLegend_Sub_Rate_C::Base_R_NonIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BaseBG) == 0x000440, "Member 'UWBP_ResultLegend_Sub_Rate_C::BaseBG' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BaseBG_LeftNonIcon) == 0x000448, "Member 'UWBP_ResultLegend_Sub_Rate_C::BaseBG_LeftNonIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BaseBG_NonIcon) == 0x000450, "Member 'UWBP_ResultLegend_Sub_Rate_C::BaseBG_NonIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BG) == 0x000458, "Member 'UWBP_ResultLegend_Sub_Rate_C::BG' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BG_02_Cover) == 0x000460, "Member 'UWBP_ResultLegend_Sub_Rate_C::BG_02_Cover' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, BG_02_Cover_02) == 0x000468, "Member 'UWBP_ResultLegend_Sub_Rate_C::BG_02_Cover_02' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Center_L) == 0x000470, "Member 'UWBP_ResultLegend_Sub_Rate_C::Center_L' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Center_R) == 0x000478, "Member 'UWBP_ResultLegend_Sub_Rate_C::Center_R' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, DMY_LegendGradeIcon_Current) == 0x000480, "Member 'UWBP_ResultLegend_Sub_Rate_C::DMY_LegendGradeIcon_Current' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, DMY_LegendGradeIcon_Next) == 0x000488, "Member 'UWBP_ResultLegend_Sub_Rate_C::DMY_LegendGradeIcon_Next' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, DSP_NUM_Grade_AddEff) == 0x000490, "Member 'UWBP_ResultLegend_Sub_Rate_C::DSP_NUM_Grade_AddEff' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Gauge) == 0x000498, "Member 'UWBP_ResultLegend_Sub_Rate_C::Gauge' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_1000) == 0x0004A0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_1000' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0_1000) == 0x0004A8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0_1000' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0001) == 0x0004B0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0001' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0001_EFF) == 0x0004B8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0001_EFF' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0010) == 0x0004C0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0010' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0010_EFF) == 0x0004C8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0010_EFF' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0100) == 0x0004D0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0100' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0100_EFF) == 0x0004D8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0100_EFF' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0_0001) == 0x0004E0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0_0001' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0_0010) == 0x0004E8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0_0010' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_0_0100) == 0x0004F0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_0_0100' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Grade_1000_EFF) == 0x0004F8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Grade_1000_EFF' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, L_Line) == 0x000500, "Member 'UWBP_ResultLegend_Sub_Rate_C::L_Line' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, L_Line_Eff) == 0x000508, "Member 'UWBP_ResultLegend_Sub_Rate_C::L_Line_Eff' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Line) == 0x000510, "Member 'UWBP_ResultLegend_Sub_Rate_C::Line' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, NUM_Grade) == 0x000518, "Member 'UWBP_ResultLegend_Sub_Rate_C::NUM_Grade' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, NUM_Grade_0000) == 0x000520, "Member 'UWBP_ResultLegend_Sub_Rate_C::NUM_Grade_0000' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, NUM_Grade_InDecrease) == 0x000528, "Member 'UWBP_ResultLegend_Sub_Rate_C::NUM_Grade_InDecrease' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, PAT_PlusMinus) == 0x000530, "Member 'UWBP_ResultLegend_Sub_Rate_C::PAT_PlusMinus' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, PlusMinus_1000) == 0x000538, "Member 'UWBP_ResultLegend_Sub_Rate_C::PlusMinus_1000' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, PlusMinus_0001) == 0x000540, "Member 'UWBP_ResultLegend_Sub_Rate_C::PlusMinus_0001' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, PlusMinus_0010) == 0x000548, "Member 'UWBP_ResultLegend_Sub_Rate_C::PlusMinus_0010' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, PlusMinus_0100) == 0x000550, "Member 'UWBP_ResultLegend_Sub_Rate_C::PlusMinus_0100' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, R_Line) == 0x000558, "Member 'UWBP_ResultLegend_Sub_Rate_C::R_Line' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, R_Line_Eff) == 0x000560, "Member 'UWBP_ResultLegend_Sub_Rate_C::R_Line_Eff' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Tri_T) == 0x000568, "Member 'UWBP_ResultLegend_Sub_Rate_C::Tri_T' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Tri_T_Btm) == 0x000570, "Member 'UWBP_ResultLegend_Sub_Rate_C::Tri_T_Btm' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Trophy) == 0x000578, "Member 'UWBP_ResultLegend_Sub_Rate_C::Trophy' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, WBP_ResultLegend_Sub_NUM_Current) == 0x000580, "Member 'UWBP_ResultLegend_Sub_Rate_C::WBP_ResultLegend_Sub_NUM_Current' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, WBP_ResultLegend_Sub_NUM_Next) == 0x000588, "Member 'UWBP_ResultLegend_Sub_Rate_C::WBP_ResultLegend_Sub_NUM_Next' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, WidgetSwitcher_GaugeBase) == 0x000590, "Member 'UWBP_ResultLegend_Sub_Rate_C::WidgetSwitcher_GaugeBase' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, WidgetSwitcher_UpDwon) == 0x000598, "Member 'UWBP_ResultLegend_Sub_Rate_C::WidgetSwitcher_UpDwon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Window_L) == 0x0005A0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Window_L' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Window_L_1) == 0x0005A8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Window_L_1' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Window_R) == 0x0005B0, "Member 'UWBP_ResultLegend_Sub_Rate_C::Window_R' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, Window_R_1) == 0x0005B8, "Member 'UWBP_ResultLegend_Sub_Rate_C::Window_R_1' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, StartAdjustingGauge) == 0x0005C0, "Member 'UWBP_ResultLegend_Sub_Rate_C::StartAdjustingGauge' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, LegendGradeIcon) == 0x0005D0, "Member 'UWBP_ResultLegend_Sub_Rate_C::LegendGradeIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ResultLegend_Sub_Rate_C, IsCountDown) == 0x000620, "Member 'UWBP_ResultLegend_Sub_Rate_C::IsCountDown' has a wrong offset!");

}

