#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_Tag

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Jukebox_Sub_Tag.WBP_Jukebox_Sub_Tag_C
// 0x0030 (0x0310 - 0x02E0)
class UWBP_Jukebox_Sub_Tag_C final : public UUserWidget
{
public:
	class UWidgetAnimation*                       Darken_Loop;                                       // 0x02E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Default_Loop;                                      // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 DSP_TagCheckPict;                                  // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        DSP_WidgetSwitcher_Tag;                            // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TagJukebox;                                        // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TagRace;                                           // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetVisibleJukeBoxOnlySubtag(bool Visible);
	void SetJukeBoxOnly(bool IsJukeboxOnly);
	void SetDarken(bool Darken);
	void Set_Checked(bool IsChecked);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Jukebox_Sub_Tag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Jukebox_Sub_Tag_C")
	}
	static class UWBP_Jukebox_Sub_Tag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Jukebox_Sub_Tag_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Jukebox_Sub_Tag_C;

}

