#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_Select

#include "Basic.hpp"

#include "WBP_Jukebox_Sub_Select_classes.hpp"
#include "WBP_Jukebox_Sub_Select_parameters.hpp"


namespace SDK
{

// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Select_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "Tick");

	Params::WBP_Jukebox_Sub_Select_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.SetActive
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Select_C::SetActive(bool IsActive_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "SetActive");

	Params::WBP_Jukebox_Sub_Select_C_SetActive Parms{};

	Parms.IsActive_0 = IsActive_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.SelectTrack
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableSound                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Select_C::SelectTrack(bool EnableSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "SelectTrack");

	Params::WBP_Jukebox_Sub_Select_C_SelectTrack Parms{};

	Parms.EnableSound = EnableSound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.SelectAlbum
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableSound                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Select_C::SelectAlbum(bool EnableSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "SelectAlbum");

	Params::WBP_Jukebox_Sub_Select_C_SelectAlbum Parms{};

	Parms.EnableSound = EnableSound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.Reflesh Control Button
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::Reflesh_Control_Button()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "Reflesh Control Button");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.OnShuffleEnable_Event
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::OnShuffleEnable_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "OnShuffleEnable_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.OnShuffleEnable
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::OnShuffleEnable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "OnShuffleEnable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.OnMoveToSelectSong_Event
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::OnMoveToSelectSong_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "OnMoveToSelectSong_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.OnMoveToAlbumSelect_Event
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::OnMoveToAlbumSelect_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "OnMoveToAlbumSelect_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.OnAlbumReflesh
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::OnAlbumReflesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "OnAlbumReflesh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.ExecuteUbergraph_WBP_Jukebox_Sub_Select
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Select_C::ExecuteUbergraph_WBP_Jukebox_Sub_Select(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "ExecuteUbergraph_WBP_Jukebox_Sub_Select");

	Params::WBP_Jukebox_Sub_Select_C_ExecuteUbergraph_WBP_Jukebox_Sub_Select Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.ControlButtonClicked
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::ControlButtonClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "ControlButtonClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Select.WBP_Jukebox_Sub_Select_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Jukebox_Sub_Select_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Select_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

