#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_Tag

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_Jukebox_Sub_Tag.WBP_Jukebox_Sub_Tag_C.SetVisibleJukeBoxOnlySubtag
// 0x0005 (0x0005 - 0x0000)
struct WBP_Jukebox_Sub_Tag_C_SetVisibleJukeBoxOnlySubtag final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_Tag_C_SetVisibleJukeBoxOnlySubtag;

// Function WBP_Jukebox_Sub_Tag.WBP_Jukebox_Sub_Tag_C.SetJukeBoxOnly
// 0x0001 (0x0001 - 0x0000)
struct WBP_Jukebox_Sub_Tag_C_SetJukeBoxOnly final
{
public:
	bool                                          IsJukeboxOnly;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_Tag_C_SetJukeBoxOnly;

// Function WBP_Jukebox_Sub_Tag.WBP_Jukebox_Sub_Tag_C.SetDarken
// 0x0018 (0x0018 - 0x0000)
struct WBP_Jukebox_Sub_Tag_C_SetDarken final
{
public:
	bool                                          Darken;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       K2Node_Select_Default;                             // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_Tag_C_SetDarken;

// Function WBP_Jukebox_Sub_Tag.WBP_Jukebox_Sub_Tag_C.Set Checked
// 0x0001 (0x0001 - 0x0000)
struct WBP_Jukebox_Sub_Tag_C_Set_Checked final
{
public:
	bool                                          IsChecked;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_Tag_C_Set_Checked;

}

