#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_MusicStatus

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Jukebox_Sub_MusicStatus.WBP_Jukebox_Sub_MusicStatus_C.SetShuffle
// 0x0008 (0x0008 - 0x0000)
struct WBP_Jukebox_Sub_MusicStatus_C_SetShuffle final
{
public:
	bool                                          Shffle;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_MusicStatus_C_SetShuffle;

// Function WBP_Jukebox_Sub_MusicStatus.WBP_Jukebox_Sub_MusicStatus_C.SetFavorite
// 0x0008 (0x0008 - 0x0000)
struct WBP_Jukebox_Sub_MusicStatus_C_SetFavorite final
{
public:
	bool                                          Favorite;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_MusicStatus_C_SetFavorite;

// Function WBP_Jukebox_Sub_MusicStatus.WBP_Jukebox_Sub_MusicStatus_C.SetDarken
// 0x0018 (0x0018 - 0x0000)
struct WBP_Jukebox_Sub_MusicStatus_C_SetDarken final
{
public:
	bool                                          Darken;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       K2Node_Select_Default;                             // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_MusicStatus_C_SetDarken;

}

