#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HonorTitleSetting_Sub_Btn

#include "Basic.hpp"

#include "WBP_HonorTitleSetting_Sub_Btn_classes.hpp"
#include "WBP_HonorTitleSetting_Sub_Btn_parameters.hpp"


namespace SDK
{

// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnBackKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnBackKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnBackKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnAddedToFocusPath");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnAcceptKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnAcceptKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnAcceptKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.IsPlateSelectedEvent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SelectedPlate                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsButtonSelected                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HonorTitleSetting_Sub_Btn_C::IsPlateSelectedEvent(int32 SelectedPlate, bool* IsButtonSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "IsPlateSelectedEvent");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_IsPlateSelectedEvent Parms{};

	Parms.SelectedPlate = SelectedPlate;

	UObject::ProcessEvent(Func, &Parms);

	if (IsButtonSelected != nullptr)
		*IsButtonSelected = Parms.IsButtonSelected;
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.ExecuteUbergraph_WBP_HonorTitleSetting_Sub_Btn
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HonorTitleSetting_Sub_Btn_C::ExecuteUbergraph_WBP_HonorTitleSetting_Sub_Btn(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "ExecuteUbergraph_WBP_HonorTitleSetting_Sub_Btn");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_ExecuteUbergraph_WBP_HonorTitleSetting_Sub_Btn Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.BindStartAndEndScrollEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::BindStartAndEndScrollEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "BindStartAndEndScrollEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.SetupUnlockedHonorTitle
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::SetupUnlockedHonorTitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "SetupUnlockedHonorTitle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.Setup Plate CurrentID
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   plateId_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HonorTitleSetting_Sub_Btn_C::Setup_Plate_CurrentID(int32 plateId_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "Setup Plate CurrentID");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_Setup_Plate_CurrentID Parms{};

	Parms.plateId_0 = plateId_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.Removed from FocusEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::Removed_from_FocusEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "Removed from FocusEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnUpKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnUpKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnUpKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnStopScrollEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnStopScrollEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnStopScrollEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnStartScrollEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnStartScrollEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnStartScrollEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.SelectedEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HonorTitleSetting_Sub_Btn_C::SelectedEvent(bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "SelectedEvent");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_SelectedEvent Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.ResetNewButtonImage
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::ResetNewButtonImage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "ResetNewButtonImage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnRightShoulderPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnRightShoulderPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnRightShoulderPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnRightKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnRightKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnRightKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnRemovedFromFocusPath");

	Params::WBP_HonorTitleSetting_Sub_Btn_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnLeftShoulderPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnLeftShoulderPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnLeftShoulderPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnLeftKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnLeftKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnLeftKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnFocus_Imp
// (BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnFocus_Imp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnFocus_Imp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnFaceButtonTopPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnFaceButtonTopPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnFaceButtonTopPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HonorTitleSetting_Sub_Btn.WBP_HonorTitleSetting_Sub_Btn_C.OnDownKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_HonorTitleSetting_Sub_Btn_C::OnDownKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HonorTitleSetting_Sub_Btn_C", "OnDownKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}

}

