#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_Attention

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Jukebox_Sub_Attention.WBP_Jukebox_Sub_Attention_C.SetInfo
// 0x0010 (0x0010 - 0x0000)
struct WBP_Jukebox_Sub_Attention_C_SetInfo final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_Jukebox_Sub_Attention_C_SetInfo;

}

