#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Friendship_Sub_Btn_Arrow_Plus

#include "Basic.hpp"

#include "WBP_Friendship_Sub_Btn_Arrow_Plus_classes.hpp"
#include "WBP_Friendship_Sub_Btn_Arrow_Plus_parameters.hpp"


namespace SDK
{

// Function WBP_Friendship_Sub_Btn_Arrow_Plus.WBP_Friendship_Sub_Btn_Arrow_Plus_C.SetEnableMouseInput
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnable_                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Friendship_Sub_Btn_Arrow_Plus_C::SetEnableMouseInput(bool IsEnable_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Friendship_Sub_Btn_Arrow_Plus_C", "SetEnableMouseInput");

	Params::WBP_Friendship_Sub_Btn_Arrow_Plus_C_SetEnableMouseInput Parms{};

	Parms.IsEnable_ = IsEnable_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Friendship_Sub_Btn_Arrow_Plus.WBP_Friendship_Sub_Btn_Arrow_Plus_C.ExecuteUbergraph_WBP_Friendship_Sub_Btn_Arrow_Plus
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Friendship_Sub_Btn_Arrow_Plus_C::ExecuteUbergraph_WBP_Friendship_Sub_Btn_Arrow_Plus(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Friendship_Sub_Btn_Arrow_Plus_C", "ExecuteUbergraph_WBP_Friendship_Sub_Btn_Arrow_Plus");

	Params::WBP_Friendship_Sub_Btn_Arrow_Plus_C_ExecuteUbergraph_WBP_Friendship_Sub_Btn_Arrow_Plus Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Friendship_Sub_Btn_Arrow_Plus.WBP_Friendship_Sub_Btn_Arrow_Plus_C.BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Friendship_Sub_Btn_Arrow_Plus_C::BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Friendship_Sub_Btn_Arrow_Plus_C", "BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Friendship_Sub_Btn_Arrow_Plus.WBP_Friendship_Sub_Btn_Arrow_Plus_C.BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Friendship_Sub_Btn_Arrow_Plus_C::BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Friendship_Sub_Btn_Arrow_Plus_C", "BndEvt__WBP_Friendship_Sub_Btn_Arrow_Plus_MouseInteraction_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

