#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_MusicPlayer_Lid

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Jukebox_Sub_MusicPlayer_Lid.WBP_Jukebox_Sub_MusicPlayer_Lid_C
// 0x0040 (0x0320 - 0x02E0)
class UWBP_Jukebox_Sub_MusicPlayer_Lid_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       SetBefore_Loop;                                    // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       SetBefore_In;                                      // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       SetAnimation_Loop;                                 // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       SetAnimation_In;                                   // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 GreenLight_SetAnimation;                           // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MusicPlayer_Lid;                                   // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsClosed;                                          // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OpenLidWithoutAnimation();
	void OpenLid();
	void Finished_E13D034845B0F35FF6F79D95011A9582();
	void Finished_AC85733245CE483D9249E39D625DFCA5();
	void Finished_8BCC725B4CE70997591A1883F9D5F535();
	void Finished_66FE31294CA47607344F1BA5DF172088();
	void ExecuteUbergraph_WBP_Jukebox_Sub_MusicPlayer_Lid(int32 EntryPoint);
	void CloseLidWithoutAnimation();
	void CloseLid();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Jukebox_Sub_MusicPlayer_Lid_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Jukebox_Sub_MusicPlayer_Lid_C")
	}
	static class UWBP_Jukebox_Sub_MusicPlayer_Lid_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Jukebox_Sub_MusicPlayer_Lid_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Jukebox_Sub_MusicPlayer_Lid_C;

}

