#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Jukebox_Sub_Setting

#include "Basic.hpp"

#include "WBP_Jukebox_Sub_Setting_classes.hpp"
#include "WBP_Jukebox_Sub_Setting_parameters.hpp"


namespace SDK
{

// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.SetActive
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Setting_C::SetActive(bool IsActive_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "SetActive");

	Params::WBP_Jukebox_Sub_Setting_C_SetActive Parms{};

	Parms.IsActive_0 = IsActive_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.RefleshUpperUI
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Setting_C::RefleshUpperUI(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "RefleshUpperUI");

	Params::WBP_Jukebox_Sub_Setting_C_RefleshUpperUI Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.RefleshJacket
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::RefleshJacket()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "RefleshJacket");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.RefleshFooter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::RefleshFooter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "RefleshFooter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnRightKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnRightKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnRightKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnLeftKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnLeftKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnLeftKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Lap                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Setting_C::OnHovered(int32 Lap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnHovered");

	Params::WBP_Jukebox_Sub_Setting_C_OnHovered Parms{};

	Parms.Lap = Lap;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnFaceButtonTopPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnFaceButtonTopPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnFaceButtonTopPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnFaceButtonLeftPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnFaceButtonLeftPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnFaceButtonLeftPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnClickedEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnClickedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnClickedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnBackKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnBackKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnBackKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.OnAcceptKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::OnAcceptKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "OnAcceptKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.ExecuteUbergraph_WBP_Jukebox_Sub_Setting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Jukebox_Sub_Setting_C::ExecuteUbergraph_WBP_Jukebox_Sub_Setting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "ExecuteUbergraph_WBP_Jukebox_Sub_Setting");

	Params::WBP_Jukebox_Sub_Setting_C_ExecuteUbergraph_WBP_Jukebox_Sub_Setting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Jukebox_Sub_Setting.WBP_Jukebox_Sub_Setting_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Jukebox_Sub_Setting_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Jukebox_Sub_Setting_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

